[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " } 

[[language]]
name = "nix"
auto-format = true
language-servers = ["nil"]

[language-server.rust-analyzer]
command = "rust-analyzer"
